### ISSUE TITLE
Please comment on "Don't send activated signal twice" patch

### ISSUE THREAD

**Issue by absurd34** [ubernostrum/django-registration#56] opened 2016-07-30 08:15 UTC
Hi James,

in the Debian packaging, there is some legacy patch:

https://sources.debian.net/src/python-django-registration/2.1.2-1/debian/patches/send_signal_only_once_when_activating_user.patch/

Not knowing better, I am still using that patch for 2.1.2 in the Debian packaging.

It would be very helpful do have your opinion on that -- i.e., is it a bug at all, can or should I drop it for 2.1.2?

Thanks!

Stephan

**Comment by ubernostrum** [comment] 2016-08-08 07:39
I'll get to this in the coming week.

**Comment by ubernostrum** [comment] 2016-08-15 05:13
I'm not sure this is a bug in the current version of django-registration; are you able to supply a test case that reliably reproduces the double-send?

**Comment by absurd34** [comment] 2016-08-15 09:54
Hi James,

On So, 2016-08-14 at 22:13 -0700, James Bennett wrote:
> I'm not sure this is a bug in the current version of django-
> registration; are you able to supply a test case that reliably
> reproduces the double-send?

no, I have not looked into that myself at all.

However, in the Debian Bug, there is a link to a StackOverflow Question
that might help:

https://stackoverflow.com/questions/18789048/django-registration-user-activated-signal-sent-twice

I am also CC'ing Tomaz and Mark, maybe they can add some useful insight here ;).

Thanks,

S

**Comment by ubernostrum** [comment] 2016-08-15 21:34
The SO question doesn't really help; if there's a minimal test case that reproduces the bug on current release, please reopen and let me know about it. Otherwise, closing due to it being a three-year-old report and django-registration being heavily updated in the meantime.

**Closed by ubernostrum** 2016-08-15 21:34 UTC
