### ISSUE TITLE
Two-step `ActivationView` runs `activate()` on HTTP GET

### ISSUE THREAD

**Issue by djramones** [ubernostrum/django-registration#242] opened 2023-10-13 02:39 UTC
Altering database state on GET requests is frowned upon. (Django, for example, is already deprecating logout via GET.)

Besides being a matter of HTTP spec compliance, there is a known issue with email services preprocessing/crawling links in the email body, [causing one-time links to be invalidated before the user gets to click them](https://www.drupal.org/project/passwordless/issues/3062482). For `django-registration` this has been reported in a [comment](https://github.com/ubernostrum/django-registration/issues/104#issuecomment-370147707) on closed issue #104.

My workaround for this currently is to simply tell the user in `activation_complete.html`, if `ActivationError` `code == "already_activated"`, that their email service could have done this and that they can already log in. At the infra level perhaps folks could also run some bot/crawler countermeasures on the activation URL path, though that's a bit more involved.

The proper fix I think is to run `activate()` only on POST, like what Django's `DeleteView` does. GET should only present a form/button, and the user needs to click to confirm activation. This also presents an opportunity for customizations like requiring a captcha solve, though I guess it's also a backwards-incompatible change.

Sorry if this is a duplicate issue, the closest report I found is #104.

**Comment by ubernostrum** [comment] 2023-10-13 22:01
This is a thing I've been thinking about for a while, but any solution has to wait for a major version bump due to being backwards-incompatible, so I'm going to leave this open as a reminder for when the 4.0 release is being planned.

**Comment by MSP-Stev** [comment] 2024-01-05 08:25
I have the same problem, but its caused by security software. The mail will be checked and the url is scanned for potential risks.

PS: I have also received registration emails where you have to enter a code, so nothing new :)

**Comment by ubernostrum** [comment] 2024-10-28 07:02
in progress and backwards-incompatible refactor:

https://github.com/ubernostrum/django-registration/tree/activation-refactor

**Comment by ubernostrum** [comment] 2024-10-29 06:00
Fixed in https://github.com/ubernostrum/django-registration/commit/5efeaa16d192fa6bace8c1d29375a1a546f7219f

There's still work to do to polish things up and get a release ready, though, so will be a bit more of a wait to get it up on PyPI.

**Closed as completed by ubernostrum** 2024-10-29 06:00 UTC
