### ISSUE TITLE
ActivationView.get_user should not filter for is_active=False

### ISSUE THREAD

**Issue by marcelchastain** [ubernostrum/django-registration#104] opened 2017-07-26 21:42 UTC
In `registration.backends.hmac.views.ActivationView`:
```python
    def get_user(self, username):
        """
        Given the verified username, look up and return the
        corresponding user account if it exists, or ``None`` if it
        doesn't.

        """
        User = get_user_model()
        lookup_kwargs = {
            User.USERNAME_FIELD: username,
            'is_active': False     # <--- astonishing!
        }
```

Re: the "principle of least astonishment":
It was very astonishing to find that activation urls were returning "The activation key foo is invalid or expired" simply because the underlying user had already been marked as active.

Apps might have more than one way of marking a user as active, and there is no harm in marking them active again.

Steps to reproduce:
1. register a new user with app configured with hmac flow
1. manually mark that user as `is_active = True`
1. attempt to follow the email activation link.

Results:
"The activation key __FOO__ is invalid or expired."

Expected Results:
Success message.

**Comment by ubernostrum** [comment] 2017-07-27 10:00
This is a duplicate of #50 and cannot be fixed until django-registration 3.0, as any fix would be backwards-incompatible.

**Closed by ubernostrum** 2017-07-27 10:00 UTC

**Comment by marcelchastain** [comment] 2017-07-30 22:18
@ubernostrum plz take another look at this issue

* Root issue is the unnecessary filter kwarg `is_active=False`.
* Fix is removing that filter kwarg
    * This is not backwards-incompatible
* Any discussion around error messaging is ancillary; not a dupe of #50

**Comment by tspavlicek** [comment] 2018-03-03 13:30
@ubernostrum I would also encourage you to reconsider this. Outlook and Hotmail email accounts follow the link when loading the activation email which activates the user and when the user actually clicks on the message, they get an activation error.
